name: build
on:
  push:
    branches:
      - "*"
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - "master"

env:
  CONNECTIQ_SDK_VERSION: 7.4.3-2024-12-11-90ec25e45
  CONNECTIQ_SDK_HOME: /opt/connectiq-sdk

jobs:
  build:
    strategy:
      matrix:
        device: [fenix7]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: "Download & install connectiq sdk"
        env:
          CONNECTIQ_SDK_URL: "https://developer.garmin.com/downloads/connect-iq/sdks"
        run: |
          wget -q ${CONNECTIQ_SDK_URL}/connectiq-sdk-lin-${CONNECTIQ_SDK_VERSION}.zip -O /tmp/connectiq-sdk.zip
          unzip /tmp/connectiq-sdk.zip -d ${{ env.CONNECTIQ_SDK_HOME }}
          mkdir -p ~/.Garmin/ConnectIQ
          unzip ${{ github.workspace }}/.github/Devices.zip -d ~/.Garmin/ConnectIQ

      - name: "Generate developer key"
        run: |
          DER=/tmp/developer.der
          PEM="$(mktemp)"
          openssl genrsa -out $PEM 4096
          openssl pkcs8 -topk8 -nocrypt -inform PEM -outform DER -in $PEM -out $DER
          rm -f $PEM
          chmod 600 $DER

      - name: "Build"
        run: |
          ${{ env.CONNECTIQ_SDK_HOME }}/bin/monkeyc -f "${{ github.workspace }}/monkey.jungle" -d ${{ matrix.device }} -o "${{ github.workspace }}/bin/BinaryNerd.prg" -y "/tmp/developer.der" -w -l 2 -r

      - uses: actions/upload-artifact@v4
        with:
          name: BinaryNerd-${{ matrix.device }}.prg
          path: bin/BinaryNerd.prg
